[package]
name = "redust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
thiserror = "1"
anyhow = "1"
rand = "0.8"
glob = "0.3"

[dev-dependencies]
tokio-test = "0.4"